// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC87sM7CRX_bpVrvHM7vjIfNbm929WwpHQ',
    appId: '1:553372392475:web:5d12de6cff9f4f1ded6cbe',
    messagingSenderId: '553372392475',
    projectId: 'chatapp-dcbef',
    authDomain: 'chatapp-dcbef.firebaseapp.com',
    storageBucket: 'chatapp-dcbef.appspot.com',
    measurementId: 'G-1MNW6E2NR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoCMJ2st8iKbCuHNyz0Ph_nHWQPxSfVno',
    appId: '1:553372392475:android:f1d17d123c1c7462ed6cbe',
    messagingSenderId: '553372392475',
    projectId: 'chatapp-dcbef',
    storageBucket: 'chatapp-dcbef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoP5ZU28xbG_yZYZ02O4gf6odXAFWgml4',
    appId: '1:553372392475:ios:af13c67f0f9b0c5ced6cbe',
    messagingSenderId: '553372392475',
    projectId: 'chatapp-dcbef',
    storageBucket: 'chatapp-dcbef.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoP5ZU28xbG_yZYZ02O4gf6odXAFWgml4',
    appId: '1:553372392475:ios:af13c67f0f9b0c5ced6cbe',
    messagingSenderId: '553372392475',
    projectId: 'chatapp-dcbef',
    storageBucket: 'chatapp-dcbef.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC87sM7CRX_bpVrvHM7vjIfNbm929WwpHQ',
    appId: '1:553372392475:web:f232a140d3baed3ded6cbe',
    messagingSenderId: '553372392475',
    projectId: 'chatapp-dcbef',
    authDomain: 'chatapp-dcbef.firebaseapp.com',
    storageBucket: 'chatapp-dcbef.appspot.com',
    measurementId: 'G-CCKML60FSE',
  );
}
